name = "terminal-site"
compatibility_date = "2026-01-25"


main = "./dist/_worker.js/index.js"

assets = { binding = "ASSETS", directory = "./dist" }

compatibility_flags = ["nodejs_compat"]

# Custom domain routes
routes = [
  { pattern = "t3rm1n4l.dev", custom_domain = true },
  { pattern = "www.t3rm1n4l.dev", custom_domain = true }
]

[build]
command = "bun run build"

